/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CineVaultPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/constants.ts
var VIEW_TYPE = "CineVaultView";

// src/views/CineVaultView.ts
var import_obsidian5 = require("obsidian");

// src/ui/onboarding.ts
function renderOnboarding(container, onCreate, onLink) {
  const onboarding = container.createDiv({
    cls: "cinevault-onboarding"
  });
  const actions = onboarding.createDiv({ cls: "cinevault-onboarding-actions" });
  const createButton = actions.createEl("button", { text: "Create new library" });
  createButton.addEventListener("click", onCreate);
  if (onLink) {
    actions.createEl("p", { text: "or" });
    const linkButton = actions.createEl("button", { text: "Link existing library" });
    linkButton.addEventListener("click", onLink);
  }
}

// src/ui/modals/CineVaultMovieActionModal.ts
var import_obsidian = require("obsidian");
var CineVaultMovieActionModal = class extends import_obsidian.Modal {
  constructor(app, movie, onSave) {
    super(app);
    this.movie = movie;
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: this.movie.title });
    contentEl.createEl("p", { text: `${this.movie.year} \u2022 ${this.movie.type}` });
    if (this.movie.poster) {
      contentEl.createEl("img", { cls: "cinevault-modal-poster" }).setAttribute("src", this.movie.poster);
    }
    contentEl.createEl("p", { text: this.movie.plot });
    const actions = contentEl.createDiv({ cls: "cinevault-modal-actions" });
    const watchedButton = actions.createEl("button", { text: "Mark as watched" });
    const toWatchButton = actions.createEl("button", { text: "To watch" });
    watchedButton.addEventListener("click", () => {
      this.onSave(true);
      this.close();
    });
    toWatchButton.addEventListener("click", () => {
      this.onSave(false);
      this.close();
    });
  }
};

// src/ui/modals/CineVaultMovieDetailModal.ts
var import_obsidian2 = require("obsidian");

// src/ui/starRating.ts
function createStarRating(container, rating, readOnly, onChange) {
  const stars = container.createDiv({ cls: "cinevault-stars" });
  const starElements = [];
  let currentRating = rating;
  for (let i = 1; i <= 5; i += 1) {
    const star = stars.createEl("span", { text: "\u2605", cls: "cinevault-star" });
    if (i <= rating)
      star.classList.add("active");
    starElements.push(star);
    if (!readOnly) {
      star.addEventListener("click", () => {
        if (currentRating === i) {
          currentRating = 0;
          starElements.forEach((element) => {
            element.classList.remove("active");
          });
        } else {
          currentRating = i;
          starElements.forEach((element, index) => {
            element.classList.toggle("active", index < i);
          });
        }
        onChange == null ? void 0 : onChange(currentRating);
      });
    } else {
      star.classList.add("readonly");
    }
  }
  return stars;
}

// src/utils.ts
function nullSafe(func, fallbackValue = null) {
  try {
    const value = func();
    return value === null || value === void 0 ? fallbackValue : value;
  } catch (e) {
    console.error("Error: ", e);
    return fallbackValue;
  }
}

// src/ui/modals/CineVaultMovieDetailModal.ts
var CineVaultMovieDetailModal = class extends import_obsidian2.Modal {
  constructor(app, movie, onRate, onRemove, onToggleWatched) {
    super(app);
    this.movie = movie;
    this.onRate = onRate;
    this.onRemove = onRemove;
    this.onToggleWatched = onToggleWatched;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    const modalContainer = contentEl.createDiv({
      cls: "cinevault-modal-container"
    });
    modalContainer.createEl("h1", {
      text: this.movie.title,
      cls: "cinevault-modal-title"
    });
    const type = nullSafe(() => this.movie.type[0].toUpperCase() + this.movie.type.slice(1), null);
    const year = nullSafe(() => this.movie.year, null);
    modalContainer.createEl("p", {
      text: `${year} - ${type}`
    });
    if (this.movie.poster) {
      modalContainer.createEl("img", { cls: "cinevault-modal-poster" }).setAttribute("src", this.movie.poster);
    }
    if (this.movie.plot) {
      const plotContainer = modalContainer.createEl("div", { cls: "cinevault-modal-plot-container" });
      const plotEl = plotContainer.createEl("p", {
        text: this.movie.plot,
        cls: "cinevault-modal-plot"
      });
      const showMoreButton = plotContainer.createEl("button", {
        text: "Show more",
        cls: "cinevault-modal-show-more cinevault-modal-show-more-hidden"
      });
      showMoreButton.addEventListener("click", () => {
        const isExpanded = plotEl.classList.toggle("expanded-plot");
        showMoreButton.setText(isExpanded ? "Show less" : "Show more");
      });
      requestAnimationFrame(() => {
        if (plotEl.scrollHeight > plotEl.clientHeight + 1) {
          showMoreButton.removeClass("cinevault-modal-show-more-hidden");
        }
      });
    }
    function rederDetailSection(type2, value) {
      const detailElement = modalContainer.createEl("div", { cls: "cinevault-modal-detail-container" });
      detailElement.createEl("p", {
        text: `${type2}:`,
        cls: "cinevault-modal-detail-label"
      });
      detailElement.createEl("p", {
        text: value,
        cls: "cinevault-modal-detail-value"
      });
    }
    modalContainer.createEl("hr");
    if (this.movie.genre) {
      rederDetailSection("Genre", this.movie.genre);
    }
    if (this.movie.director) {
      rederDetailSection("Director", this.movie.director);
    }
    if (this.movie.actors) {
      rederDetailSection("Actors", this.movie.actors);
    }
    modalContainer.createEl("hr");
    const ratingContainer = modalContainer.createDiv({
      cls: "cinevault-modal-rating-container"
    });
    ratingContainer.createEl("div", { text: "Rating", cls: "cinevault-modal-rating-label" });
    const stars = createStarRating(ratingContainer, this.movie.starRating, false, (rating) => {
      this.onRate(rating);
    });
    stars.classList.add("cinevault-modal-stars");
    if (this.movie.ratings) {
      const externalRatingsContainer = modalContainer.createDiv({
        cls: "cinevault-modal-external-ratings"
      });
      for (const rating of this.movie.ratings) {
        const ratingEl = externalRatingsContainer.createDiv({ cls: "cinevault-modal-external-rating-element" });
        ratingEl.createEl("div", { text: rating.Source, cls: "cinevault-modal-external-rating-source" });
        ratingEl.createEl("div", { text: rating.Value, cls: "cinevault-modal-external-rating-value" });
      }
    }
    const actions = modalContainer.createDiv({ cls: "cinevault-modal-actions" });
    const toggleWatchedLabel = this.movie.watched ? "Mark as to watch" : "Mark as watched";
    const toggleWatchedButton = actions.createEl("button", { text: toggleWatchedLabel });
    const removeButton = actions.createEl("button", { text: "Remove", cls: "cinevault-danger" });
    toggleWatchedButton.addEventListener("click", () => {
      this.onToggleWatched();
      this.close();
    });
    removeButton.addEventListener("click", () => {
      this.onRemove();
      this.close();
    });
  }
};

// src/ui/JsonFileSuggestModal.ts
var import_obsidian3 = require("obsidian");
var JsonFileSuggestModal = class extends import_obsidian3.SuggestModal {
  constructor(app, onSelect) {
    super(app);
    this.onSelect = onSelect;
    this.jsonFiles = this.app.vault.getFiles().filter((f) => f.extension === "json");
    this.setPlaceholder("Select a JSON file from your vault...");
  }
  getSuggestions(query) {
    const lowerQuery = query.toLowerCase();
    return this.jsonFiles.filter(
      (file) => file.path.toLowerCase().includes(lowerQuery)
    );
  }
  renderSuggestion(file, el) {
    el.createEl("div", { text: file.path });
  }
  onChooseSuggestion(file, evt) {
    this.onSelect(file);
  }
};

// src/services/libraryStorage.ts
var FOLDER = "cinevault-json";
var DEFAULT_NAME = "cinevault.json";
function getDefaultPath() {
  return `${FOLDER}/${DEFAULT_NAME}`;
}
function getFolder() {
  return FOLDER;
}
function createEmptyMovie() {
  return {
    id: crypto.randomUUID(),
    imdbId: "",
    title: "",
    year: "",
    rated: "",
    released: "",
    runtime: "",
    genre: "",
    director: "",
    writer: "",
    actors: "",
    plot: "",
    language: "",
    country: "",
    awards: "",
    poster: "",
    posterLocal: "",
    ratings: [],
    metascore: "",
    imdbRating: "",
    imdbVotes: "",
    type: "",
    dvd: "",
    boxOffice: "",
    production: "",
    website: "",
    totalSeasons: "",
    tomatoURL: "",
    tomatoMeter: "",
    tomatoImage: "",
    tomatoRating: "",
    tomatoReviews: "",
    tomatoFresh: "",
    tomatoRotten: "",
    tomatoConsensus: "",
    tomatoUserMeter: "",
    tomatoUserRating: "",
    tomatoUserReviews: "",
    starRating: 0,
    watched: false,
    notes: ""
  };
}
function createDefaultData() {
  const now = new Date().toISOString();
  return {
    schemaVersion: 1,
    createdAt: now,
    updatedAt: now,
    libraryName: "CineVault",
    owner: "",
    source: "CineVault",
    movies: []
  };
}
function normalizeData(data) {
  return {
    ...data,
    movies: data.movies.map((movie) => ({
      ...createEmptyMovie(),
      ...movie,
      year: movie.year ? String(movie.year) : "",
      starRating: typeof movie.starRating === "number" ? movie.starRating : 0
    }))
  };
}
async function ensureFolder(app) {
  if (!app.vault.getAbstractFileByPath(FOLDER)) {
    await app.vault.createFolder(FOLDER);
  }
}
async function createJsonFile(app) {
  await ensureFolder(app);
  const existing = app.vault.getAbstractFileByPath(getDefaultPath());
  const filename = existing ? `cinevault-${Date.now()}.json` : DEFAULT_NAME;
  const path = `${FOLDER}/${filename}`;
  return app.vault.create(path, JSON.stringify(createDefaultData(), null, 2));
}
async function loadLocalFile(app, file) {
  const raw = await app.vault.read(file);
  const parsed = JSON.parse(raw);
  if (!parsed || !Array.isArray(parsed.movies)) {
    throw new Error("Formato JSON non valido");
  }
  return normalizeData(parsed);
}
async function saveLocalData(app, file, data) {
  await app.vault.modify(file, JSON.stringify(data, null, 2));
}

// src/services/omdbService.ts
var import_obsidian4 = require("obsidian");
async function searchOmdb(query, apiKey) {
  if (!apiKey) {
    return [];
  }
  try {
    const url = `https://www.omdbapi.com/?apikey=${apiKey}&s=${encodeURIComponent(query)}`;
    const response = await (0, import_obsidian4.requestUrl)(url);
    const data = response.json;
    if (data == null ? void 0 : data.Search) {
      return data.Search.map((item) => ({
        imdbId: item.imdbID,
        title: item.Title,
        year: item.Year,
        type: item.Type,
        poster: item.Poster && item.Poster !== "N/A" ? item.Poster : "",
        plot: ""
      }));
    }
    return [];
  } catch (error) {
    console.error("Error searching OMDb:", error);
    return [];
  }
}
async function getOmdbDetails(imdbId, apiKey, depth = 0) {
  if (depth >= 3) {
    console.error(`Failed to fetch movie details after ${depth} attempts`);
    return null;
  }
  if (!apiKey) {
    return null;
  }
  try {
    const url = `https://www.omdbapi.com/?apikey=${apiKey}&i=${imdbId}&plot=full&tomatoes=true`;
    const response = await (0, import_obsidian4.requestUrl)(url);
    const data = response.json;
    if (data.Response !== "True") {
      console.error("OMDb API returned error response", data);
      return null;
    }
    return data;
  } catch (error) {
    console.error("Error fetching movie details, retrying...", error);
    return getOmdbDetails(imdbId, apiKey, depth + 1);
  }
}

// src/views/CineVaultView.ts
var CineVaultView = class extends import_obsidian5.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.file = null;
    this.data = null;
    this.activeTab = "toWatch";
    this.moviesContainer = null;
    this.viewMode = "grid";
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "CineVault";
  }
  // Provide a custom icon for the view's tab
  getIcon() {
    return "clapperboard";
  }
  async onOpen() {
    var _a;
    this.viewMode = (_a = this.plugin.viewMode) != null ? _a : "grid";
    await this.initializeData();
    await this.render();
  }
  async render() {
    const container = this.containerEl.children[1];
    container.empty();
    const header = container.createDiv({ cls: "cinevault-header" });
    header.createEl("h1", {
      text: "CineVault",
      cls: "cinevault-title"
    });
    header.createEl("p", {
      text: "CineVault allow you to manageyour favorites movie and tv library into your vault. Search OMDb, rate titles, and store your collection in a json file within your vault.",
      cls: "cinevault-header-text"
    });
    if (!this.data) {
      renderOnboarding(container, async () => {
        this.file = await createJsonFile(this.plugin.app);
        if (this.file) {
          await this.plugin.setLocalJsonPath(this.file.path);
        }
        await this.loadFile(this.file);
        await this.render();
      }, () => {
        new JsonFileSuggestModal(this.plugin.app, async (file) => {
          await this.loadFile(file);
          await this.render();
        }).open();
      });
      return;
    }
    const searchBox = container.createDiv({ cls: "cinevault-search" });
    const searchInput = searchBox.createEl("input", {
      cls: "cinevault-search-input",
      attr: {
        placeholder: "Search"
      }
    });
    const resultsList = searchBox.createDiv({ cls: "cinevault-search-results" });
    const content = container.createDiv({ cls: "cinevault-content" });
    this.moviesContainer = content;
    this.renderMovies(content);
    let searchTimeout = null;
    searchInput.addEventListener("input", () => {
      if (searchTimeout)
        window.clearTimeout(searchTimeout);
      searchTimeout = window.setTimeout(async () => {
        const query = searchInput.value.trim();
        await this.renderSearchResults(resultsList, query);
      }, 350);
    });
  }
  renderMovies(container) {
    container.empty();
    if (!this.data) {
      container.createEl("p", { text: "No library loaded." });
      return;
    }
    const watched = this.data.movies.filter((movie) => movie.watched);
    const toWatch = this.data.movies.filter((movie) => !movie.watched);
    const tabsContainer = container.createDiv({ cls: "cinevault-tabs-container" });
    const tabHeader = tabsContainer.createDiv({ cls: "cinevault-tab-header" });
    const tabButtons = tabHeader.createDiv({ cls: "cinevault-tab-buttons" });
    const viewToggle = tabHeader.createDiv({ cls: "cinevault-view-toggle" });
    const toWatchButton = tabButtons.createEl("button", {
      cls: "cinevault-tab-button",
      text: `To Watch (${toWatch.length})`
    });
    const watchedButton = tabButtons.createEl("button", {
      cls: "cinevault-tab-button",
      text: `Watched (${watched.length})`
    });
    const gridButton = viewToggle.createEl("button", {
      cls: "cinevault-view-button",
      attr: { "aria-label": "Grid view", title: "Grid view" }
    });
    const listButton = viewToggle.createEl("button", {
      cls: "cinevault-view-button",
      attr: { "aria-label": "List view", title: "List view" }
    });
    (0, import_obsidian5.setIcon)(gridButton, "layout-grid");
    (0, import_obsidian5.setIcon)(listButton, "list");
    if (this.activeTab === "toWatch") {
      toWatchButton.classList.add("cinevault-tab-button-active");
    } else {
      watchedButton.classList.add("cinevault-tab-button-active");
    }
    if (this.viewMode === "grid") {
      gridButton.classList.add("cinevault-view-button-active");
    } else {
      listButton.classList.add("cinevault-view-button-active");
    }
    const tabContent = tabsContainer.createDiv({ cls: "cinevault-tab-content" });
    const activeMovies = this.activeTab === "toWatch" ? toWatch : watched;
    const activeTitle = this.activeTab === "toWatch" ? "To Watch" : "Watched";
    this.renderMovieSection(tabContent, activeTitle, activeMovies);
    toWatchButton.addEventListener("click", () => {
      if (this.activeTab === "toWatch")
        return;
      this.activeTab = "toWatch";
      this.renderMovies(container);
    });
    watchedButton.addEventListener("click", () => {
      if (this.activeTab === "watched")
        return;
      this.activeTab = "watched";
      this.renderMovies(container);
    });
    gridButton.addEventListener("click", async () => {
      if (this.viewMode === "grid")
        return;
      this.viewMode = "grid";
      await this.plugin.setViewMode("grid");
      this.renderMovies(container);
    });
    listButton.addEventListener("click", async () => {
      if (this.viewMode === "list")
        return;
      this.viewMode = "list";
      await this.plugin.setViewMode("list");
      this.renderMovies(container);
    });
  }
  renderMovieSection(container, title, movies) {
    const section = container.createDiv({ cls: "cinevault-section" });
    section.createEl("h3", { text: title });
    if (movies.length === 0) {
      section.createEl("p", { text: "No movies in this list." });
      return;
    }
    const list = section.createDiv({
      cls: this.viewMode === "grid" ? "cinevault-movie-grid" : "cinevault-movie-list"
    });
    if (this.viewMode === "grid") {
      this.renderMovieGrid(list, movies);
    } else {
      this.renderMovieList(list, movies);
    }
  }
  renderMovieGrid(container, movies) {
    movies.forEach((movie) => {
      const card = container.createDiv({ cls: "cinevault-movie-card" });
      card.createEl("img", { cls: "cinevault-movie-poster" }).setAttribute("src", movie.poster);
      card.createEl("div", { text: movie.title, cls: "cinevault-movie-title" });
      const type = nullSafe(() => movie.type[0].toUpperCase() + movie.type.slice(1), null);
      const year = nullSafe(() => movie.year, null);
      card.createEl("div", { text: `${year} - ${type}` || "", cls: "cinevault-movie-year" });
      card.addEventListener("click", () => this.openMovieDetails(movie));
    });
  }
  renderMovieList(container, movies) {
    movies.forEach((movie) => {
      const row = container.createDiv({ cls: "cinevault-movie-row" });
      const poster = row.createEl("img", { cls: "cinevault-movie-thumbnail" });
      poster.setAttribute("src", movie.poster || "");
      const info = row.createDiv({ cls: "cinevault-movie-info" });
      info.createEl("div", { text: movie.title, cls: "cinevault-movie-title" });
      const type = nullSafe(() => movie.type[0].toUpperCase() + movie.type.slice(1), null);
      const year = nullSafe(() => movie.year, null);
      info.createEl("div", { text: `${year} - ${type}` || "", cls: "cinevault-movie-year" });
      row.addEventListener("click", () => this.openMovieDetails(movie));
    });
  }
  openMovieDetails(movie) {
    new CineVaultMovieDetailModal(this.plugin.app, movie, async (rating) => {
      if (!this.data)
        return;
      movie.starRating = rating;
      await this.saveData();
      this.refreshMovies();
    }, async () => {
      if (!this.data)
        return;
      this.data.movies = this.data.movies.filter((item) => item.id !== movie.id);
      await this.saveData();
      this.refreshMovies();
    }, async () => {
      if (!this.data)
        return;
      movie.watched = !movie.watched;
      await this.saveData();
      this.refreshMovies();
    }).open();
  }
  refreshMovies() {
    if (!this.moviesContainer)
      return;
    this.renderMovies(this.moviesContainer);
  }
  getJsonFiles() {
    return this.plugin.app.vault.getFiles().filter((file) => file.extension === "json");
  }
  async initializeData() {
    const localPath = this.plugin.localJsonPath;
    if (localPath) {
      const localFile = this.plugin.app.vault.getAbstractFileByPath(localPath);
      if (localFile instanceof import_obsidian5.TFile) {
        await this.loadFile(localFile);
        return;
      }
    }
    this.file = null;
    this.data = null;
  }
  async loadFile(file) {
    try {
      const parsed = await loadLocalFile(this.plugin.app, file);
      this.file = file;
      this.data = parsed;
      await this.plugin.setLocalJsonPath(file.path);
    } catch (error) {
      this.data = null;
      this.file = null;
      new import_obsidian5.Notice("Unable to read the JSON file.");
    }
  }
  async saveData() {
    if (!this.data)
      return;
    this.data.updatedAt = new Date().toISOString();
    if (this.file) {
      await saveLocalData(this.plugin.app, this.file, this.data);
    }
  }
  async renderSearchResults(container, query) {
    container.empty();
    if (!query || query.length < 2)
      return;
    const results = await searchOmdb(query, this.plugin.omdbApiKey);
    if (results.length === 0) {
      container.createEl("div", { text: "No results found.", cls: "cinevault-search-empty" });
      return;
    }
    results.forEach((result) => {
      const item = container.createDiv({ cls: "cinevault-search-item" });
      if (result.poster) {
        item.createEl("img", { cls: "cinevault-search-poster" }).setAttribute("src", result.poster);
      }
      const info = item.createDiv({ cls: "cinevault-search-info" });
      info.createEl("div", { text: result.title, cls: "cinevault-search-title" });
      info.createEl("div", { text: result.year, cls: "cinevault-search-year" });
      item.addEventListener("click", () => {
        new CineVaultMovieActionModal(this.plugin.app, result, async (watched) => {
          if (!this.data)
            return;
          const existing = this.data.movies.find((movie) => movie.imdbId === result.imdbId);
          if (existing) {
            existing.watched = watched;
          } else {
            new import_obsidian5.Notice(`Loading details for ${result.title}...`);
            const details = await getOmdbDetails(result.imdbId, this.plugin.omdbApiKey);
            if (!details) {
              new import_obsidian5.Notice("Unable to load movie details.");
              return;
            }
            const newMovie = createEmptyMovie();
            newMovie.imdbId = details.imdbID || result.imdbId;
            newMovie.title = details.Title || result.title;
            newMovie.year = details.Year || result.year;
            newMovie.rated = details.Rated || "";
            newMovie.released = details.Released || "";
            newMovie.runtime = details.Runtime || "";
            newMovie.genre = details.Genre || "";
            newMovie.director = details.Director || "";
            newMovie.writer = details.Writer || "";
            newMovie.actors = details.Actors || "";
            newMovie.plot = details.Plot || result.plot;
            newMovie.language = details.Language || "";
            newMovie.country = details.Country || "";
            newMovie.awards = details.Awards || "";
            newMovie.poster = details.Poster && details.Poster !== "N/A" ? details.Poster : result.poster;
            newMovie.posterLocal = "";
            newMovie.ratings = details.Ratings || [];
            newMovie.metascore = details.Metascore || "";
            newMovie.imdbRating = details.imdbRating || "";
            newMovie.imdbVotes = details.imdbVotes || "";
            newMovie.type = details.Type || result.type;
            newMovie.dvd = details.DVD || "";
            newMovie.boxOffice = details.BoxOffice || "";
            newMovie.production = details.Production || "";
            newMovie.website = details.Website || "";
            newMovie.totalSeasons = details.totalSeasons || "";
            newMovie.watched = watched;
            this.data.movies.push(newMovie);
          }
          await this.saveData();
          this.render();
        }).open();
      });
    });
  }
};

// src/settings/CineVaultSettingTab.ts
var import_obsidian6 = require("obsidian");
var CineVaultSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian6.Setting(containerEl).setName("Configuration").setHeading();
    new import_obsidian6.Setting(containerEl).setName("OMDb API key").setDesc("Enter your OMDb API key. You can get one for free at omdbapi.com").addText((text) => text.setPlaceholder("Enter your API key").setValue(this.plugin.omdbApiKey).onChange(async (value) => {
      await this.plugin.setOmdbApiKey(value);
    }));
    new import_obsidian6.Setting(containerEl).setName("Linked local library").setDesc(
      this.plugin.localJsonPath ? `Local file: ${this.plugin.localJsonPath}` : "No local library linked"
    ).addDropdown((drop) => {
      var _a;
      const files = this.app.vault.getFiles().filter((f) => f.extension === "json");
      const options = { "": "-- None --" };
      files.forEach((f) => options[f.path] = f.path);
      drop.addOptions(options).setValue((_a = this.plugin.localJsonPath) != null ? _a : "").onChange(async (value) => {
        const path = value || null;
        await this.plugin.setLocalJsonPath(path);
        await this.refreshOpenViews();
        this.display();
      });
    }).addButton((button) => button.setButtonText("Unlink local").setDisabled(!this.plugin.localJsonPath).onClick(async () => {
      await this.plugin.setLocalJsonPath(null);
      await this.refreshOpenViews();
      this.display();
    }));
    new import_obsidian6.Setting(containerEl).setName("Create new library").setDesc("Create a new empty local library from scratch. This will unlink any external library.").addButton((button) => button.setButtonText("Create library").onClick(async () => {
      await this.createNewLibrary();
    }));
    new import_obsidian6.Setting(containerEl).setName("Export library").setDesc("Save a copy of your library JSON to a file.").addButton((button) => button.setButtonText("Export JSON").onClick(async () => {
      await this.exportLibraryJson();
    }));
    new import_obsidian6.Setting(containerEl).setName("Bugfix").setHeading();
    new import_obsidian6.Setting(containerEl).setName("Report issues").setDesc("If you encounter any issues with the plugin, please report them. Your feedback is invaluable for improving CineVault!").addButton((button) => button.setButtonText("GitHub").onClick(() => {
      window.open("https://github.com/vscaperrotta/obsidian-cinevault/issues", "_blank");
    }));
    new import_obsidian6.Setting(containerEl).setName("Support").setHeading();
    new import_obsidian6.Setting(containerEl).setName("Donate").setDesc(
      "If you like this plugin, consider donating to support continued development."
    ).addButton((bt) => {
      bt.buttonEl.outerHTML = "<a href='https://ko-fi.com/T6T01TX807' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://storage.ko-fi.com/cdn/kofi6.png?v=6' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a>";
    });
  }
  async exportLibraryJson() {
    try {
      const content = await this.getLibraryJsonContent();
      if (!content) {
        new import_obsidian6.Notice("No library file found to export.");
        return;
      }
      const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
      const exportPath = `cinevault-export-${timestamp}.json`;
      let finalPath = exportPath;
      let counter = 1;
      while (this.app.vault.getAbstractFileByPath(finalPath)) {
        finalPath = `cinevault-export-${timestamp}-${counter}.json`;
        counter++;
      }
      await this.app.vault.create(finalPath, content);
      new import_obsidian6.Notice(`Library exported to ${finalPath}`);
    } catch (error) {
      console.error("[CineVault] Export library error", error);
      new import_obsidian6.Notice("Unable to export the library.");
    }
  }
  async createNewLibrary() {
    const confirmed = window.confirm(
      "Create a new empty CineVault library? This will unlink any external library and reset your local library data."
    );
    if (!confirmed)
      return;
    try {
      const defaultFile = this.app.vault.getAbstractFileByPath(getDefaultPath());
      let createdFile;
      if (defaultFile instanceof import_obsidian6.TFile) {
        await saveLocalData(this.app, defaultFile, createDefaultData());
        createdFile = defaultFile;
      } else {
        createdFile = await createJsonFile(this.app);
      }
      if (createdFile) {
        await this.plugin.setLocalJsonPath(createdFile.path);
      }
      await this.refreshOpenViews();
      this.display();
      new import_obsidian6.Notice("New library created.");
    } catch (error) {
      console.error("[CineVault] Create new library error", error);
      new import_obsidian6.Notice("Unable to create a new library.");
    }
  }
  async getLibraryJsonContent() {
    if (this.plugin.localJsonPath) {
      const localPath = this.plugin.localJsonPath;
      const file = this.app.vault.getAbstractFileByPath(localPath);
      if (file instanceof import_obsidian6.TFile) {
        return this.app.vault.read(file);
      }
    }
    const defaultFile = this.app.vault.getAbstractFileByPath(getDefaultPath());
    if (defaultFile instanceof import_obsidian6.TFile) {
      return this.app.vault.read(defaultFile);
    }
    const folder = getFolder();
    const fallback = this.app.vault.getFiles().find((file) => file.extension === "json" && file.path.startsWith(`${folder}/`));
    if (fallback) {
      return this.app.vault.read(fallback);
    }
    return null;
  }
  async refreshOpenViews() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    for (const leaf of leaves) {
      if (leaf.view instanceof CineVaultView) {
        await leaf.view.onOpen();
      }
    }
  }
};

// src/main.ts
var CineVaultPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.localJsonPath = null;
    this.omdbApiKey = "";
    this.viewMode = "grid";
  }
  // Initialize the plugin and set up event listeners
  async onload() {
    await this.loadPluginData();
    this.addSettingTab(new CineVaultSettingTab(this.app, this));
    this.registerView(
      VIEW_TYPE,
      (leaf) => new CineVaultView(leaf, this)
    );
    this.addRibbonIcon("clapperboard", "CineVault", async () => {
      await this.openNewTab();
    });
  }
  // Unmount the status bar element when the plugin is disabled
  onunload() {
  }
  async loadPluginData() {
    var _a, _b, _c;
    const data = await this.loadData();
    this.localJsonPath = (_a = data == null ? void 0 : data.localJsonPath) != null ? _a : null;
    this.omdbApiKey = (_b = data == null ? void 0 : data.omdbApiKey) != null ? _b : "";
    this.viewMode = (_c = data == null ? void 0 : data.viewMode) != null ? _c : "grid";
  }
  // externalJsonPath removed; no-op placeholder removed
  async setOmdbApiKey(apiKey) {
    this.omdbApiKey = apiKey;
    await this.savePluginData();
  }
  async setViewMode(viewMode) {
    this.viewMode = viewMode;
    await this.savePluginData();
  }
  async savePluginData() {
    const data = {
      omdbApiKey: this.omdbApiKey,
      viewMode: this.viewMode
    };
    if (this.localJsonPath) {
      data.localJsonPath = this.localJsonPath;
    }
    await this.saveData(data);
  }
  async setLocalJsonPath(path) {
    this.localJsonPath = path;
    await this.savePluginData();
  }
  // Open a new tab with the "CineVault" view type
  async openNewTab() {
    const existingLeaves = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    if (existingLeaves.length > 0) {
      this.app.workspace.revealLeaf(existingLeaves[0]);
      return;
    }
    const leaf = this.app.workspace.getLeaf(true);
    await leaf.setViewState({
      type: VIEW_TYPE,
      active: true
    });
  }
};
